/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */


@class NSMapTable;
@protocol SBIconViewDelegate;

@interface SBIconViewMap : NSObject  {
	NSMapTable* _iconViewsForIcons;
	id<SBIconViewDelegate> _iconViewdelegate;
	NSMapTable* _recycledIconViewsByType;
	NSMapTable* _labels;
	NSMapTable* _badges;
}
+(id)homescreenMap;
+(Class)iconViewClassForIcon:(id)icon location:(int)location;
-(id)init;
-(void)dealloc;
-(id)mappedIconViewForIcon:(id)icon;
-(id)_iconViewForIcon:(id)icon;
-(id)iconViewForIcon:(id)icon;
-(void)addIconView:(id)view forIcon:(id)icon;
-(void)purgeIconFromMap:(id)map;
-(void)_recycleIconView:(id)view;
-(void)recycleIconMapping:(id)mapping;
-(void)recycleAndPurgeAll;
-(id)releaseIconLabelForIcon:(id)icon;
-(void)captureIconLabel:(id)label forIcon:(id)icon;
-(void)_modelListAddedIcon:(id)icon;
-(void)_modelRemovedIcon:(id)icon;
-(void)_modelReloadedIcons;
-(void)_modelReloadedState;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
@end

